// Code generated by mockery. DO NOT EDIT.

package broadcast

import (
	broadcast "github.com/rusmanplatd/goravelframework/contracts/broadcast"
	mock "github.com/stretchr/testify/mock"
)

// Broadcaster is an autogenerated mock type for the Broadcaster type
type Broadcaster struct {
	mock.Mock
}

type Broadcaster_Expecter struct {
	mock *mock.Mock
}

func (_m *Broadcaster) EXPECT() *Broadcaster_Expecter {
	return &Broadcaster_Expecter{mock: &_m.Mock}
}

// Auth provides a mock function with given fields: request
func (_m *Broadcaster) Auth(request interface{}) (interface{}, error) {
	ret := _m.Called(request)

	if len(ret) == 0 {
		panic("no return value specified for Auth")
	}

	var r0 interface{}
	var r1 error
	if rf, ok := ret.Get(0).(func(interface{}) (interface{}, error)); ok {
		return rf(request)
	}
	if rf, ok := ret.Get(0).(func(interface{}) interface{}); ok {
		r0 = rf(request)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(interface{})
		}
	}

	if rf, ok := ret.Get(1).(func(interface{}) error); ok {
		r1 = rf(request)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Broadcaster_Auth_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Auth'
type Broadcaster_Auth_Call struct {
	*mock.Call
}

// Auth is a helper method to define mock.On call
//   - request interface{}
func (_e *Broadcaster_Expecter) Auth(request interface{}) *Broadcaster_Auth_Call {
	return &Broadcaster_Auth_Call{Call: _e.mock.On("Auth", request)}
}

func (_c *Broadcaster_Auth_Call) Run(run func(request interface{})) *Broadcaster_Auth_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(interface{}))
	})
	return _c
}

func (_c *Broadcaster_Auth_Call) Return(_a0 interface{}, _a1 error) *Broadcaster_Auth_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *Broadcaster_Auth_Call) RunAndReturn(run func(interface{}) (interface{}, error)) *Broadcaster_Auth_Call {
	_c.Call.Return(run)
	return _c
}

// Broadcast provides a mock function with given fields: channels, event, payload
func (_m *Broadcaster) Broadcast(channels []broadcast.Channel, event string, payload map[string]interface{}) error {
	ret := _m.Called(channels, event, payload)

	if len(ret) == 0 {
		panic("no return value specified for Broadcast")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func([]broadcast.Channel, string, map[string]interface{}) error); ok {
		r0 = rf(channels, event, payload)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Broadcaster_Broadcast_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Broadcast'
type Broadcaster_Broadcast_Call struct {
	*mock.Call
}

// Broadcast is a helper method to define mock.On call
//   - channels []broadcast.Channel
//   - event string
//   - payload map[string]interface{}
func (_e *Broadcaster_Expecter) Broadcast(channels interface{}, event interface{}, payload interface{}) *Broadcaster_Broadcast_Call {
	return &Broadcaster_Broadcast_Call{Call: _e.mock.On("Broadcast", channels, event, payload)}
}

func (_c *Broadcaster_Broadcast_Call) Run(run func(channels []broadcast.Channel, event string, payload map[string]interface{})) *Broadcaster_Broadcast_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].([]broadcast.Channel), args[1].(string), args[2].(map[string]interface{}))
	})
	return _c
}

func (_c *Broadcaster_Broadcast_Call) Return(_a0 error) *Broadcaster_Broadcast_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *Broadcaster_Broadcast_Call) RunAndReturn(run func([]broadcast.Channel, string, map[string]interface{}) error) *Broadcaster_Broadcast_Call {
	_c.Call.Return(run)
	return _c
}

// Channel provides a mock function with given fields: channel, callback, options
func (_m *Broadcaster) Channel(channel string, callback broadcast.ChannelAuthCallback, options ...broadcast.ChannelOption) broadcast.Broadcaster {
	_va := make([]interface{}, len(options))
	for _i := range options {
		_va[_i] = options[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, channel, callback)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	if len(ret) == 0 {
		panic("no return value specified for Channel")
	}

	var r0 broadcast.Broadcaster
	if rf, ok := ret.Get(0).(func(string, broadcast.ChannelAuthCallback, ...broadcast.ChannelOption) broadcast.Broadcaster); ok {
		r0 = rf(channel, callback, options...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(broadcast.Broadcaster)
		}
	}

	return r0
}

// Broadcaster_Channel_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Channel'
type Broadcaster_Channel_Call struct {
	*mock.Call
}

// Channel is a helper method to define mock.On call
//   - channel string
//   - callback broadcast.ChannelAuthCallback
//   - options ...broadcast.ChannelOption
func (_e *Broadcaster_Expecter) Channel(channel interface{}, callback interface{}, options ...interface{}) *Broadcaster_Channel_Call {
	return &Broadcaster_Channel_Call{Call: _e.mock.On("Channel",
		append([]interface{}{channel, callback}, options...)...)}
}

func (_c *Broadcaster_Channel_Call) Run(run func(channel string, callback broadcast.ChannelAuthCallback, options ...broadcast.ChannelOption)) *Broadcaster_Channel_Call {
	_c.Call.Run(func(args mock.Arguments) {
		variadicArgs := make([]broadcast.ChannelOption, len(args)-2)
		for i, a := range args[2:] {
			if a != nil {
				variadicArgs[i] = a.(broadcast.ChannelOption)
			}
		}
		run(args[0].(string), args[1].(broadcast.ChannelAuthCallback), variadicArgs...)
	})
	return _c
}

func (_c *Broadcaster_Channel_Call) Return(_a0 broadcast.Broadcaster) *Broadcaster_Channel_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *Broadcaster_Channel_Call) RunAndReturn(run func(string, broadcast.ChannelAuthCallback, ...broadcast.ChannelOption) broadcast.Broadcaster) *Broadcaster_Channel_Call {
	_c.Call.Return(run)
	return _c
}

// ResolveAuthenticatedUser provides a mock function with given fields: request
func (_m *Broadcaster) ResolveAuthenticatedUser(request interface{}) (map[string]interface{}, error) {
	ret := _m.Called(request)

	if len(ret) == 0 {
		panic("no return value specified for ResolveAuthenticatedUser")
	}

	var r0 map[string]interface{}
	var r1 error
	if rf, ok := ret.Get(0).(func(interface{}) (map[string]interface{}, error)); ok {
		return rf(request)
	}
	if rf, ok := ret.Get(0).(func(interface{}) map[string]interface{}); ok {
		r0 = rf(request)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(map[string]interface{})
		}
	}

	if rf, ok := ret.Get(1).(func(interface{}) error); ok {
		r1 = rf(request)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Broadcaster_ResolveAuthenticatedUser_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ResolveAuthenticatedUser'
type Broadcaster_ResolveAuthenticatedUser_Call struct {
	*mock.Call
}

// ResolveAuthenticatedUser is a helper method to define mock.On call
//   - request interface{}
func (_e *Broadcaster_Expecter) ResolveAuthenticatedUser(request interface{}) *Broadcaster_ResolveAuthenticatedUser_Call {
	return &Broadcaster_ResolveAuthenticatedUser_Call{Call: _e.mock.On("ResolveAuthenticatedUser", request)}
}

func (_c *Broadcaster_ResolveAuthenticatedUser_Call) Run(run func(request interface{})) *Broadcaster_ResolveAuthenticatedUser_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(interface{}))
	})
	return _c
}

func (_c *Broadcaster_ResolveAuthenticatedUser_Call) Return(_a0 map[string]interface{}, _a1 error) *Broadcaster_ResolveAuthenticatedUser_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *Broadcaster_ResolveAuthenticatedUser_Call) RunAndReturn(run func(interface{}) (map[string]interface{}, error)) *Broadcaster_ResolveAuthenticatedUser_Call {
	_c.Call.Return(run)
	return _c
}

// ResolveAuthenticatedUserUsing provides a mock function with given fields: callback
func (_m *Broadcaster) ResolveAuthenticatedUserUsing(callback func(interface{}) map[string]interface{}) {
	_m.Called(callback)
}

// Broadcaster_ResolveAuthenticatedUserUsing_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ResolveAuthenticatedUserUsing'
type Broadcaster_ResolveAuthenticatedUserUsing_Call struct {
	*mock.Call
}

// ResolveAuthenticatedUserUsing is a helper method to define mock.On call
//   - callback func(interface{}) map[string]interface{}
func (_e *Broadcaster_Expecter) ResolveAuthenticatedUserUsing(callback interface{}) *Broadcaster_ResolveAuthenticatedUserUsing_Call {
	return &Broadcaster_ResolveAuthenticatedUserUsing_Call{Call: _e.mock.On("ResolveAuthenticatedUserUsing", callback)}
}

func (_c *Broadcaster_ResolveAuthenticatedUserUsing_Call) Run(run func(callback func(interface{}) map[string]interface{})) *Broadcaster_ResolveAuthenticatedUserUsing_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(func(interface{}) map[string]interface{}))
	})
	return _c
}

func (_c *Broadcaster_ResolveAuthenticatedUserUsing_Call) Return() *Broadcaster_ResolveAuthenticatedUserUsing_Call {
	_c.Call.Return()
	return _c
}

func (_c *Broadcaster_ResolveAuthenticatedUserUsing_Call) RunAndReturn(run func(func(interface{}) map[string]interface{})) *Broadcaster_ResolveAuthenticatedUserUsing_Call {
	_c.Run(run)
	return _c
}

// ValidAuthenticationResponse provides a mock function with given fields: request, result
func (_m *Broadcaster) ValidAuthenticationResponse(request interface{}, result interface{}) (interface{}, error) {
	ret := _m.Called(request, result)

	if len(ret) == 0 {
		panic("no return value specified for ValidAuthenticationResponse")
	}

	var r0 interface{}
	var r1 error
	if rf, ok := ret.Get(0).(func(interface{}, interface{}) (interface{}, error)); ok {
		return rf(request, result)
	}
	if rf, ok := ret.Get(0).(func(interface{}, interface{}) interface{}); ok {
		r0 = rf(request, result)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(interface{})
		}
	}

	if rf, ok := ret.Get(1).(func(interface{}, interface{}) error); ok {
		r1 = rf(request, result)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Broadcaster_ValidAuthenticationResponse_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ValidAuthenticationResponse'
type Broadcaster_ValidAuthenticationResponse_Call struct {
	*mock.Call
}

// ValidAuthenticationResponse is a helper method to define mock.On call
//   - request interface{}
//   - result interface{}
func (_e *Broadcaster_Expecter) ValidAuthenticationResponse(request interface{}, result interface{}) *Broadcaster_ValidAuthenticationResponse_Call {
	return &Broadcaster_ValidAuthenticationResponse_Call{Call: _e.mock.On("ValidAuthenticationResponse", request, result)}
}

func (_c *Broadcaster_ValidAuthenticationResponse_Call) Run(run func(request interface{}, result interface{})) *Broadcaster_ValidAuthenticationResponse_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(interface{}), args[1].(interface{}))
	})
	return _c
}

func (_c *Broadcaster_ValidAuthenticationResponse_Call) Return(_a0 interface{}, _a1 error) *Broadcaster_ValidAuthenticationResponse_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *Broadcaster_ValidAuthenticationResponse_Call) RunAndReturn(run func(interface{}, interface{}) (interface{}, error)) *Broadcaster_ValidAuthenticationResponse_Call {
	_c.Call.Return(run)
	return _c
}

// NewBroadcaster creates a new instance of Broadcaster. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewBroadcaster(t interface {
	mock.TestingT
	Cleanup(func())
}) *Broadcaster {
	mock := &Broadcaster{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
