// Code generated by mockery. DO NOT EDIT.

package broadcast

import mock "github.com/stretchr/testify/mock"

// BroadcastConnection is an autogenerated mock type for the BroadcastConnection type
type BroadcastConnection struct {
	mock.Mock
}

type BroadcastConnection_Expecter struct {
	mock *mock.Mock
}

func (_m *BroadcastConnection) EXPECT() *BroadcastConnection_Expecter {
	return &BroadcastConnection_Expecter{mock: &_m.Mock}
}

// BroadcastConnection provides a mock function with no fields
func (_m *BroadcastConnection) BroadcastConnection() string {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for BroadcastConnection")
	}

	var r0 string
	if rf, ok := ret.Get(0).(func() string); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(string)
	}

	return r0
}

// BroadcastConnection_BroadcastConnection_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'BroadcastConnection'
type BroadcastConnection_BroadcastConnection_Call struct {
	*mock.Call
}

// BroadcastConnection is a helper method to define mock.On call
func (_e *BroadcastConnection_Expecter) BroadcastConnection() *BroadcastConnection_BroadcastConnection_Call {
	return &BroadcastConnection_BroadcastConnection_Call{Call: _e.mock.On("BroadcastConnection")}
}

func (_c *BroadcastConnection_BroadcastConnection_Call) Run(run func()) *BroadcastConnection_BroadcastConnection_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *BroadcastConnection_BroadcastConnection_Call) Return(_a0 string) *BroadcastConnection_BroadcastConnection_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *BroadcastConnection_BroadcastConnection_Call) RunAndReturn(run func() string) *BroadcastConnection_BroadcastConnection_Call {
	_c.Call.Return(run)
	return _c
}

// NewBroadcastConnection creates a new instance of BroadcastConnection. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewBroadcastConnection(t interface {
	mock.TestingT
	Cleanup(func())
}) *BroadcastConnection {
	mock := &BroadcastConnection{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
