// Code generated by mockery. DO NOT EDIT.

package broadcast

import mock "github.com/stretchr/testify/mock"

// BroadcastVia is an autogenerated mock type for the BroadcastVia type
type BroadcastVia struct {
	mock.Mock
}

type BroadcastVia_Expecter struct {
	mock *mock.Mock
}

func (_m *BroadcastVia) EXPECT() *BroadcastVia_Expecter {
	return &BroadcastVia_Expecter{mock: &_m.Mock}
}

// BroadcastVia provides a mock function with no fields
func (_m *BroadcastVia) BroadcastVia() string {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for BroadcastVia")
	}

	var r0 string
	if rf, ok := ret.Get(0).(func() string); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(string)
	}

	return r0
}

// BroadcastVia_BroadcastVia_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'BroadcastVia'
type BroadcastVia_BroadcastVia_Call struct {
	*mock.Call
}

// BroadcastVia is a helper method to define mock.On call
func (_e *BroadcastVia_Expecter) BroadcastVia() *BroadcastVia_BroadcastVia_Call {
	return &BroadcastVia_BroadcastVia_Call{Call: _e.mock.On("BroadcastVia")}
}

func (_c *BroadcastVia_BroadcastVia_Call) Run(run func()) *BroadcastVia_BroadcastVia_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *BroadcastVia_BroadcastVia_Call) Return(_a0 string) *BroadcastVia_BroadcastVia_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *BroadcastVia_BroadcastVia_Call) RunAndReturn(run func() string) *BroadcastVia_BroadcastVia_Call {
	_c.Call.Return(run)
	return _c
}

// NewBroadcastVia creates a new instance of BroadcastVia. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewBroadcastVia(t interface {
	mock.TestingT
	Cleanup(func())
}) *BroadcastVia {
	mock := &BroadcastVia{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
