// Code generated by mockery. DO NOT EDIT.

package broadcast

import mock "github.com/stretchr/testify/mock"

// BroadcastConnections is an autogenerated mock type for the BroadcastConnections type
type BroadcastConnections struct {
	mock.Mock
}

type BroadcastConnections_Expecter struct {
	mock *mock.Mock
}

func (_m *BroadcastConnections) EXPECT() *BroadcastConnections_Expecter {
	return &BroadcastConnections_Expecter{mock: &_m.Mock}
}

// BroadcastConnections provides a mock function with no fields
func (_m *BroadcastConnections) BroadcastConnections() []string {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for BroadcastConnections")
	}

	var r0 []string
	if rf, ok := ret.Get(0).(func() []string); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]string)
		}
	}

	return r0
}

// BroadcastConnections_BroadcastConnections_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'BroadcastConnections'
type BroadcastConnections_BroadcastConnections_Call struct {
	*mock.Call
}

// BroadcastConnections is a helper method to define mock.On call
func (_e *BroadcastConnections_Expecter) BroadcastConnections() *BroadcastConnections_BroadcastConnections_Call {
	return &BroadcastConnections_BroadcastConnections_Call{Call: _e.mock.On("BroadcastConnections")}
}

func (_c *BroadcastConnections_BroadcastConnections_Call) Run(run func()) *BroadcastConnections_BroadcastConnections_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *BroadcastConnections_BroadcastConnections_Call) Return(_a0 []string) *BroadcastConnections_BroadcastConnections_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *BroadcastConnections_BroadcastConnections_Call) RunAndReturn(run func() []string) *BroadcastConnections_BroadcastConnections_Call {
	_c.Call.Return(run)
	return _c
}

// NewBroadcastConnections creates a new instance of BroadcastConnections. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewBroadcastConnections(t interface {
	mock.TestingT
	Cleanup(func())
}) *BroadcastConnections {
	mock := &BroadcastConnections{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
