// Code generated by mockery. DO NOT EDIT.

package broadcast

import mock "github.com/stretchr/testify/mock"

// BroadcastWith is an autogenerated mock type for the BroadcastWith type
type BroadcastWith struct {
	mock.Mock
}

type BroadcastWith_Expecter struct {
	mock *mock.Mock
}

func (_m *BroadcastWith) EXPECT() *BroadcastWith_Expecter {
	return &BroadcastWith_Expecter{mock: &_m.Mock}
}

// BroadcastWith provides a mock function with no fields
func (_m *BroadcastWith) BroadcastWith() map[string]interface{} {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for BroadcastWith")
	}

	var r0 map[string]interface{}
	if rf, ok := ret.Get(0).(func() map[string]interface{}); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(map[string]interface{})
		}
	}

	return r0
}

// BroadcastWith_BroadcastWith_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'BroadcastWith'
type BroadcastWith_BroadcastWith_Call struct {
	*mock.Call
}

// BroadcastWith is a helper method to define mock.On call
func (_e *BroadcastWith_Expecter) BroadcastWith() *BroadcastWith_BroadcastWith_Call {
	return &BroadcastWith_BroadcastWith_Call{Call: _e.mock.On("BroadcastWith")}
}

func (_c *BroadcastWith_BroadcastWith_Call) Run(run func()) *BroadcastWith_BroadcastWith_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *BroadcastWith_BroadcastWith_Call) Return(_a0 map[string]interface{}) *BroadcastWith_BroadcastWith_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *BroadcastWith_BroadcastWith_Call) RunAndReturn(run func() map[string]interface{}) *BroadcastWith_BroadcastWith_Call {
	_c.Call.Return(run)
	return _c
}

// NewBroadcastWith creates a new instance of BroadcastWith. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewBroadcastWith(t interface {
	mock.TestingT
	Cleanup(func())
}) *BroadcastWith {
	mock := &BroadcastWith{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
