// Code generated by mockery. DO NOT EDIT.

package broadcast

import mock "github.com/stretchr/testify/mock"

// BroadcastQueue is an autogenerated mock type for the BroadcastQueue type
type BroadcastQueue struct {
	mock.Mock
}

type BroadcastQueue_Expecter struct {
	mock *mock.Mock
}

func (_m *BroadcastQueue) EXPECT() *BroadcastQueue_Expecter {
	return &BroadcastQueue_Expecter{mock: &_m.Mock}
}

// BroadcastQueue provides a mock function with no fields
func (_m *BroadcastQueue) BroadcastQueue() string {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for BroadcastQueue")
	}

	var r0 string
	if rf, ok := ret.Get(0).(func() string); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(string)
	}

	return r0
}

// BroadcastQueue_BroadcastQueue_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'BroadcastQueue'
type BroadcastQueue_BroadcastQueue_Call struct {
	*mock.Call
}

// BroadcastQueue is a helper method to define mock.On call
func (_e *BroadcastQueue_Expecter) BroadcastQueue() *BroadcastQueue_BroadcastQueue_Call {
	return &BroadcastQueue_BroadcastQueue_Call{Call: _e.mock.On("BroadcastQueue")}
}

func (_c *BroadcastQueue_BroadcastQueue_Call) Run(run func()) *BroadcastQueue_BroadcastQueue_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *BroadcastQueue_BroadcastQueue_Call) Return(_a0 string) *BroadcastQueue_BroadcastQueue_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *BroadcastQueue_BroadcastQueue_Call) RunAndReturn(run func() string) *BroadcastQueue_BroadcastQueue_Call {
	_c.Call.Return(run)
	return _c
}

// NewBroadcastQueue creates a new instance of BroadcastQueue. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewBroadcastQueue(t interface {
	mock.TestingT
	Cleanup(func())
}) *BroadcastQueue {
	mock := &BroadcastQueue{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
