// Code generated by mockery. DO NOT EDIT.

package broadcast

import mock "github.com/stretchr/testify/mock"

// BroadcastAs is an autogenerated mock type for the BroadcastAs type
type BroadcastAs struct {
	mock.Mock
}

type BroadcastAs_Expecter struct {
	mock *mock.Mock
}

func (_m *BroadcastAs) EXPECT() *BroadcastAs_Expecter {
	return &BroadcastAs_Expecter{mock: &_m.Mock}
}

// BroadcastAs provides a mock function with no fields
func (_m *BroadcastAs) BroadcastAs() string {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for BroadcastAs")
	}

	var r0 string
	if rf, ok := ret.Get(0).(func() string); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(string)
	}

	return r0
}

// BroadcastAs_BroadcastAs_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'BroadcastAs'
type BroadcastAs_BroadcastAs_Call struct {
	*mock.Call
}

// BroadcastAs is a helper method to define mock.On call
func (_e *BroadcastAs_Expecter) BroadcastAs() *BroadcastAs_BroadcastAs_Call {
	return &BroadcastAs_BroadcastAs_Call{Call: _e.mock.On("BroadcastAs")}
}

func (_c *BroadcastAs_BroadcastAs_Call) Run(run func()) *BroadcastAs_BroadcastAs_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *BroadcastAs_BroadcastAs_Call) Return(_a0 string) *BroadcastAs_BroadcastAs_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *BroadcastAs_BroadcastAs_Call) RunAndReturn(run func() string) *BroadcastAs_BroadcastAs_Call {
	_c.Call.Return(run)
	return _c
}

// NewBroadcastAs creates a new instance of BroadcastAs. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewBroadcastAs(t interface {
	mock.TestingT
	Cleanup(func())
}) *BroadcastAs {
	mock := &BroadcastAs{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
