// Code generated by mockery. DO NOT EDIT.

package broadcast

import mock "github.com/stretchr/testify/mock"

// ChannelAuthCallback is an autogenerated mock type for the ChannelAuthCallback type
type ChannelAuthCallback struct {
	mock.Mock
}

type ChannelAuthCallback_Expecter struct {
	mock *mock.Mock
}

func (_m *ChannelAuthCallback) EXPECT() *ChannelAuthCallback_Expecter {
	return &ChannelAuthCallback_Expecter{mock: &_m.Mock}
}

// Execute provides a mock function with given fields: user, params
func (_m *ChannelAuthCallback) Execute(user interface{}, params ...interface{}) interface{} {
	var _ca []interface{}
	_ca = append(_ca, user)
	_ca = append(_ca, params...)
	ret := _m.Called(_ca...)

	if len(ret) == 0 {
		panic("no return value specified for Execute")
	}

	var r0 interface{}
	if rf, ok := ret.Get(0).(func(interface{}, ...interface{}) interface{}); ok {
		r0 = rf(user, params...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(interface{})
		}
	}

	return r0
}

// ChannelAuthCallback_Execute_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Execute'
type ChannelAuthCallback_Execute_Call struct {
	*mock.Call
}

// Execute is a helper method to define mock.On call
//   - user interface{}
//   - params ...interface{}
func (_e *ChannelAuthCallback_Expecter) Execute(user interface{}, params ...interface{}) *ChannelAuthCallback_Execute_Call {
	return &ChannelAuthCallback_Execute_Call{Call: _e.mock.On("Execute",
		append([]interface{}{user}, params...)...)}
}

func (_c *ChannelAuthCallback_Execute_Call) Run(run func(user interface{}, params ...interface{})) *ChannelAuthCallback_Execute_Call {
	_c.Call.Run(func(args mock.Arguments) {
		variadicArgs := make([]interface{}, len(args)-1)
		for i, a := range args[1:] {
			if a != nil {
				variadicArgs[i] = a.(interface{})
			}
		}
		run(args[0].(interface{}), variadicArgs...)
	})
	return _c
}

func (_c *ChannelAuthCallback_Execute_Call) Return(_a0 interface{}) *ChannelAuthCallback_Execute_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *ChannelAuthCallback_Execute_Call) RunAndReturn(run func(interface{}, ...interface{}) interface{}) *ChannelAuthCallback_Execute_Call {
	_c.Call.Return(run)
	return _c
}

// NewChannelAuthCallback creates a new instance of ChannelAuthCallback. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewChannelAuthCallback(t interface {
	mock.TestingT
	Cleanup(func())
}) *ChannelAuthCallback {
	mock := &ChannelAuthCallback{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
