// Code generated by mockery. DO NOT EDIT.

package broadcast

import mock "github.com/stretchr/testify/mock"

// Channel is an autogenerated mock type for the Channel type
type Channel struct {
	mock.Mock
}

type Channel_Expecter struct {
	mock *mock.Mock
}

func (_m *Channel) EXPECT() *Channel_Expecter {
	return &Channel_Expecter{mock: &_m.Mock}
}

// GetName provides a mock function with no fields
func (_m *Channel) GetName() string {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetName")
	}

	var r0 string
	if rf, ok := ret.Get(0).(func() string); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(string)
	}

	return r0
}

// Channel_GetName_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetName'
type Channel_GetName_Call struct {
	*mock.Call
}

// GetName is a helper method to define mock.On call
func (_e *Channel_Expecter) GetName() *Channel_GetName_Call {
	return &Channel_GetName_Call{Call: _e.mock.On("GetName")}
}

func (_c *Channel_GetName_Call) Run(run func()) *Channel_GetName_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *Channel_GetName_Call) Return(_a0 string) *Channel_GetName_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *Channel_GetName_Call) RunAndReturn(run func() string) *Channel_GetName_Call {
	_c.Call.Return(run)
	return _c
}

// IsPresence provides a mock function with no fields
func (_m *Channel) IsPresence() bool {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for IsPresence")
	}

	var r0 bool
	if rf, ok := ret.Get(0).(func() bool); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(bool)
	}

	return r0
}

// Channel_IsPresence_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'IsPresence'
type Channel_IsPresence_Call struct {
	*mock.Call
}

// IsPresence is a helper method to define mock.On call
func (_e *Channel_Expecter) IsPresence() *Channel_IsPresence_Call {
	return &Channel_IsPresence_Call{Call: _e.mock.On("IsPresence")}
}

func (_c *Channel_IsPresence_Call) Run(run func()) *Channel_IsPresence_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *Channel_IsPresence_Call) Return(_a0 bool) *Channel_IsPresence_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *Channel_IsPresence_Call) RunAndReturn(run func() bool) *Channel_IsPresence_Call {
	_c.Call.Return(run)
	return _c
}

// IsPrivate provides a mock function with no fields
func (_m *Channel) IsPrivate() bool {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for IsPrivate")
	}

	var r0 bool
	if rf, ok := ret.Get(0).(func() bool); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(bool)
	}

	return r0
}

// Channel_IsPrivate_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'IsPrivate'
type Channel_IsPrivate_Call struct {
	*mock.Call
}

// IsPrivate is a helper method to define mock.On call
func (_e *Channel_Expecter) IsPrivate() *Channel_IsPrivate_Call {
	return &Channel_IsPrivate_Call{Call: _e.mock.On("IsPrivate")}
}

func (_c *Channel_IsPrivate_Call) Run(run func()) *Channel_IsPrivate_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *Channel_IsPrivate_Call) Return(_a0 bool) *Channel_IsPrivate_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *Channel_IsPrivate_Call) RunAndReturn(run func() bool) *Channel_IsPrivate_Call {
	_c.Call.Return(run)
	return _c
}

// NewChannel creates a new instance of Channel. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewChannel(t interface {
	mock.TestingT
	Cleanup(func())
}) *Channel {
	mock := &Channel{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
