// Code generated by mockery. DO NOT EDIT.

package broadcast

import mock "github.com/stretchr/testify/mock"

// DontBroadcastToCurrentUser is an autogenerated mock type for the DontBroadcastToCurrentUser type
type DontBroadcastToCurrentUser struct {
	mock.Mock
}

type DontBroadcastToCurrentUser_Expecter struct {
	mock *mock.Mock
}

func (_m *DontBroadcastToCurrentUser) EXPECT() *DontBroadcastToCurrentUser_Expecter {
	return &DontBroadcastToCurrentUser_Expecter{mock: &_m.Mock}
}

// DontBroadcastToCurrentUser provides a mock function with no fields
func (_m *DontBroadcastToCurrentUser) DontBroadcastToCurrentUser() {
	_m.Called()
}

// DontBroadcastToCurrentUser_DontBroadcastToCurrentUser_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DontBroadcastToCurrentUser'
type DontBroadcastToCurrentUser_DontBroadcastToCurrentUser_Call struct {
	*mock.Call
}

// DontBroadcastToCurrentUser is a helper method to define mock.On call
func (_e *DontBroadcastToCurrentUser_Expecter) DontBroadcastToCurrentUser() *DontBroadcastToCurrentUser_DontBroadcastToCurrentUser_Call {
	return &DontBroadcastToCurrentUser_DontBroadcastToCurrentUser_Call{Call: _e.mock.On("DontBroadcastToCurrentUser")}
}

func (_c *DontBroadcastToCurrentUser_DontBroadcastToCurrentUser_Call) Run(run func()) *DontBroadcastToCurrentUser_DontBroadcastToCurrentUser_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *DontBroadcastToCurrentUser_DontBroadcastToCurrentUser_Call) Return() *DontBroadcastToCurrentUser_DontBroadcastToCurrentUser_Call {
	_c.Call.Return()
	return _c
}

func (_c *DontBroadcastToCurrentUser_DontBroadcastToCurrentUser_Call) RunAndReturn(run func()) *DontBroadcastToCurrentUser_DontBroadcastToCurrentUser_Call {
	_c.Run(run)
	return _c
}

// NewDontBroadcastToCurrentUser creates a new instance of DontBroadcastToCurrentUser. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewDontBroadcastToCurrentUser(t interface {
	mock.TestingT
	Cleanup(func())
}) *DontBroadcastToCurrentUser {
	mock := &DontBroadcastToCurrentUser{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
