// Code generated by mockery. DO NOT EDIT.

package broadcast

import mock "github.com/stretchr/testify/mock"

// HasBroadcastChannel is an autogenerated mock type for the HasBroadcastChannel type
type HasBroadcastChannel struct {
	mock.Mock
}

type HasBroadcastChannel_Expecter struct {
	mock *mock.Mock
}

func (_m *HasBroadcastChannel) EXPECT() *HasBroadcastChannel_Expecter {
	return &HasBroadcastChannel_Expecter{mock: &_m.Mock}
}

// BroadcastChannelRoute provides a mock function with no fields
func (_m *HasBroadcastChannel) BroadcastChannelRoute() string {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for BroadcastChannelRoute")
	}

	var r0 string
	if rf, ok := ret.Get(0).(func() string); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(string)
	}

	return r0
}

// HasBroadcastChannel_BroadcastChannelRoute_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'BroadcastChannelRoute'
type HasBroadcastChannel_BroadcastChannelRoute_Call struct {
	*mock.Call
}

// BroadcastChannelRoute is a helper method to define mock.On call
func (_e *HasBroadcastChannel_Expecter) BroadcastChannelRoute() *HasBroadcastChannel_BroadcastChannelRoute_Call {
	return &HasBroadcastChannel_BroadcastChannelRoute_Call{Call: _e.mock.On("BroadcastChannelRoute")}
}

func (_c *HasBroadcastChannel_BroadcastChannelRoute_Call) Run(run func()) *HasBroadcastChannel_BroadcastChannelRoute_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *HasBroadcastChannel_BroadcastChannelRoute_Call) Return(_a0 string) *HasBroadcastChannel_BroadcastChannelRoute_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *HasBroadcastChannel_BroadcastChannelRoute_Call) RunAndReturn(run func() string) *HasBroadcastChannel_BroadcastChannelRoute_Call {
	_c.Call.Return(run)
	return _c
}

// NewHasBroadcastChannel creates a new instance of HasBroadcastChannel. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewHasBroadcastChannel(t interface {
	mock.TestingT
	Cleanup(func())
}) *HasBroadcastChannel {
	mock := &HasBroadcastChannel{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
