// Code generated by mockery. DO NOT EDIT.

package broadcast

import (
	broadcast "github.com/goravel/framework/contracts/broadcast"
	mock "github.com/stretchr/testify/mock"
)

// InteractsWithBroadcasting is an autogenerated mock type for the InteractsWithBroadcasting type
type InteractsWithBroadcasting struct {
	mock.Mock
}

type InteractsWithBroadcasting_Expecter struct {
	mock *mock.Mock
}

func (_m *InteractsWithBroadcasting) EXPECT() *InteractsWithBroadcasting_Expecter {
	return &InteractsWithBroadcasting_Expecter{mock: &_m.Mock}
}

// BroadcastConnections provides a mock function with no fields
func (_m *InteractsWithBroadcasting) BroadcastConnections() []string {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for BroadcastConnections")
	}

	var r0 []string
	if rf, ok := ret.Get(0).(func() []string); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]string)
		}
	}

	return r0
}

// InteractsWithBroadcasting_BroadcastConnections_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'BroadcastConnections'
type InteractsWithBroadcasting_BroadcastConnections_Call struct {
	*mock.Call
}

// BroadcastConnections is a helper method to define mock.On call
func (_e *InteractsWithBroadcasting_Expecter) BroadcastConnections() *InteractsWithBroadcasting_BroadcastConnections_Call {
	return &InteractsWithBroadcasting_BroadcastConnections_Call{Call: _e.mock.On("BroadcastConnections")}
}

func (_c *InteractsWithBroadcasting_BroadcastConnections_Call) Run(run func()) *InteractsWithBroadcasting_BroadcastConnections_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *InteractsWithBroadcasting_BroadcastConnections_Call) Return(_a0 []string) *InteractsWithBroadcasting_BroadcastConnections_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *InteractsWithBroadcasting_BroadcastConnections_Call) RunAndReturn(run func() []string) *InteractsWithBroadcasting_BroadcastConnections_Call {
	_c.Call.Return(run)
	return _c
}

// BroadcastVia provides a mock function with given fields: connection
func (_m *InteractsWithBroadcasting) BroadcastVia(connection string) broadcast.InteractsWithBroadcasting {
	ret := _m.Called(connection)

	if len(ret) == 0 {
		panic("no return value specified for BroadcastVia")
	}

	var r0 broadcast.InteractsWithBroadcasting
	if rf, ok := ret.Get(0).(func(string) broadcast.InteractsWithBroadcasting); ok {
		r0 = rf(connection)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(broadcast.InteractsWithBroadcasting)
		}
	}

	return r0
}

// InteractsWithBroadcasting_BroadcastVia_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'BroadcastVia'
type InteractsWithBroadcasting_BroadcastVia_Call struct {
	*mock.Call
}

// BroadcastVia is a helper method to define mock.On call
//   - connection string
func (_e *InteractsWithBroadcasting_Expecter) BroadcastVia(connection interface{}) *InteractsWithBroadcasting_BroadcastVia_Call {
	return &InteractsWithBroadcasting_BroadcastVia_Call{Call: _e.mock.On("BroadcastVia", connection)}
}

func (_c *InteractsWithBroadcasting_BroadcastVia_Call) Run(run func(connection string)) *InteractsWithBroadcasting_BroadcastVia_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string))
	})
	return _c
}

func (_c *InteractsWithBroadcasting_BroadcastVia_Call) Return(_a0 broadcast.InteractsWithBroadcasting) *InteractsWithBroadcasting_BroadcastVia_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *InteractsWithBroadcasting_BroadcastVia_Call) RunAndReturn(run func(string) broadcast.InteractsWithBroadcasting) *InteractsWithBroadcasting_BroadcastVia_Call {
	_c.Call.Return(run)
	return _c
}

// NewInteractsWithBroadcasting creates a new instance of InteractsWithBroadcasting. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewInteractsWithBroadcasting(t interface {
	mock.TestingT
	Cleanup(func())
}) *InteractsWithBroadcasting {
	mock := &InteractsWithBroadcasting{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
