// Code generated by mockery. DO NOT EDIT.

package broadcast

import (
	broadcast "github.com/goravel/framework/contracts/broadcast"
	mock "github.com/stretchr/testify/mock"
)

// Manager is an autogenerated mock type for the Manager type
type Manager struct {
	mock.Mock
}

type Manager_Expecter struct {
	mock *mock.Mock
}

func (_m *Manager) EXPECT() *Manager_Expecter {
	return &Manager_Expecter{mock: &_m.Mock}
}

// Connection provides a mock function with given fields: name
func (_m *Manager) Connection(name ...string) (broadcast.Broadcaster, error) {
	_va := make([]interface{}, len(name))
	for _i := range name {
		_va[_i] = name[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	if len(ret) == 0 {
		panic("no return value specified for Connection")
	}

	var r0 broadcast.Broadcaster
	var r1 error
	if rf, ok := ret.Get(0).(func(...string) (broadcast.Broadcaster, error)); ok {
		return rf(name...)
	}
	if rf, ok := ret.Get(0).(func(...string) broadcast.Broadcaster); ok {
		r0 = rf(name...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(broadcast.Broadcaster)
		}
	}

	if rf, ok := ret.Get(1).(func(...string) error); ok {
		r1 = rf(name...)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Manager_Connection_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Connection'
type Manager_Connection_Call struct {
	*mock.Call
}

// Connection is a helper method to define mock.On call
//   - name ...string
func (_e *Manager_Expecter) Connection(name ...interface{}) *Manager_Connection_Call {
	return &Manager_Connection_Call{Call: _e.mock.On("Connection",
		append([]interface{}{}, name...)...)}
}

func (_c *Manager_Connection_Call) Run(run func(name ...string)) *Manager_Connection_Call {
	_c.Call.Run(func(args mock.Arguments) {
		variadicArgs := make([]string, len(args)-0)
		for i, a := range args[0:] {
			if a != nil {
				variadicArgs[i] = a.(string)
			}
		}
		run(variadicArgs...)
	})
	return _c
}

func (_c *Manager_Connection_Call) Return(_a0 broadcast.Broadcaster, _a1 error) *Manager_Connection_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *Manager_Connection_Call) RunAndReturn(run func(...string) (broadcast.Broadcaster, error)) *Manager_Connection_Call {
	_c.Call.Return(run)
	return _c
}

// Driver provides a mock function with given fields: name
func (_m *Manager) Driver(name ...string) (broadcast.Broadcaster, error) {
	_va := make([]interface{}, len(name))
	for _i := range name {
		_va[_i] = name[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	if len(ret) == 0 {
		panic("no return value specified for Driver")
	}

	var r0 broadcast.Broadcaster
	var r1 error
	if rf, ok := ret.Get(0).(func(...string) (broadcast.Broadcaster, error)); ok {
		return rf(name...)
	}
	if rf, ok := ret.Get(0).(func(...string) broadcast.Broadcaster); ok {
		r0 = rf(name...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(broadcast.Broadcaster)
		}
	}

	if rf, ok := ret.Get(1).(func(...string) error); ok {
		r1 = rf(name...)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Manager_Driver_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Driver'
type Manager_Driver_Call struct {
	*mock.Call
}

// Driver is a helper method to define mock.On call
//   - name ...string
func (_e *Manager_Expecter) Driver(name ...interface{}) *Manager_Driver_Call {
	return &Manager_Driver_Call{Call: _e.mock.On("Driver",
		append([]interface{}{}, name...)...)}
}

func (_c *Manager_Driver_Call) Run(run func(name ...string)) *Manager_Driver_Call {
	_c.Call.Run(func(args mock.Arguments) {
		variadicArgs := make([]string, len(args)-0)
		for i, a := range args[0:] {
			if a != nil {
				variadicArgs[i] = a.(string)
			}
		}
		run(variadicArgs...)
	})
	return _c
}

func (_c *Manager_Driver_Call) Return(_a0 broadcast.Broadcaster, _a1 error) *Manager_Driver_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *Manager_Driver_Call) RunAndReturn(run func(...string) (broadcast.Broadcaster, error)) *Manager_Driver_Call {
	_c.Call.Return(run)
	return _c
}

// NewManager creates a new instance of Manager. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewManager(t interface {
	mock.TestingT
	Cleanup(func())
}) *Manager {
	mock := &Manager{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
