// Code generated by mockery. DO NOT EDIT.

package broadcast

import (
	broadcast "github.com/rusmanplatd/goravelframework/contracts/broadcast"
	mock "github.com/stretchr/testify/mock"
)

// ShouldBroadcast is an autogenerated mock type for the ShouldBroadcast type
type ShouldBroadcast struct {
	mock.Mock
}

type ShouldBroadcast_Expecter struct {
	mock *mock.Mock
}

func (_m *ShouldBroadcast) EXPECT() *ShouldBroadcast_Expecter {
	return &ShouldBroadcast_Expecter{mock: &_m.Mock}
}

// BroadcastOn provides a mock function with no fields
func (_m *ShouldBroadcast) BroadcastOn() []broadcast.Channel {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for BroadcastOn")
	}

	var r0 []broadcast.Channel
	if rf, ok := ret.Get(0).(func() []broadcast.Channel); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]broadcast.Channel)
		}
	}

	return r0
}

// ShouldBroadcast_BroadcastOn_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'BroadcastOn'
type ShouldBroadcast_BroadcastOn_Call struct {
	*mock.Call
}

// BroadcastOn is a helper method to define mock.On call
func (_e *ShouldBroadcast_Expecter) BroadcastOn() *ShouldBroadcast_BroadcastOn_Call {
	return &ShouldBroadcast_BroadcastOn_Call{Call: _e.mock.On("BroadcastOn")}
}

func (_c *ShouldBroadcast_BroadcastOn_Call) Run(run func()) *ShouldBroadcast_BroadcastOn_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *ShouldBroadcast_BroadcastOn_Call) Return(_a0 []broadcast.Channel) *ShouldBroadcast_BroadcastOn_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *ShouldBroadcast_BroadcastOn_Call) RunAndReturn(run func() []broadcast.Channel) *ShouldBroadcast_BroadcastOn_Call {
	_c.Call.Return(run)
	return _c
}

// NewShouldBroadcast creates a new instance of ShouldBroadcast. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewShouldBroadcast(t interface {
	mock.TestingT
	Cleanup(func())
}) *ShouldBroadcast {
	mock := &ShouldBroadcast{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
