// Code generated by mockery. DO NOT EDIT.

package broadcast

import (
	broadcast "github.com/rusmanplatd/goravelframework/contracts/broadcast"
	mock "github.com/stretchr/testify/mock"
)

// ShouldBroadcastNow is an autogenerated mock type for the ShouldBroadcastNow type
type ShouldBroadcastNow struct {
	mock.Mock
}

type ShouldBroadcastNow_Expecter struct {
	mock *mock.Mock
}

func (_m *ShouldBroadcastNow) EXPECT() *ShouldBroadcastNow_Expecter {
	return &ShouldBroadcastNow_Expecter{mock: &_m.Mock}
}

// BroadcastOn provides a mock function with no fields
func (_m *ShouldBroadcastNow) BroadcastOn() []broadcast.Channel {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for BroadcastOn")
	}

	var r0 []broadcast.Channel
	if rf, ok := ret.Get(0).(func() []broadcast.Channel); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]broadcast.Channel)
		}
	}

	return r0
}

// ShouldBroadcastNow_BroadcastOn_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'BroadcastOn'
type ShouldBroadcastNow_BroadcastOn_Call struct {
	*mock.Call
}

// BroadcastOn is a helper method to define mock.On call
func (_e *ShouldBroadcastNow_Expecter) BroadcastOn() *ShouldBroadcastNow_BroadcastOn_Call {
	return &ShouldBroadcastNow_BroadcastOn_Call{Call: _e.mock.On("BroadcastOn")}
}

func (_c *ShouldBroadcastNow_BroadcastOn_Call) Run(run func()) *ShouldBroadcastNow_BroadcastOn_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *ShouldBroadcastNow_BroadcastOn_Call) Return(_a0 []broadcast.Channel) *ShouldBroadcastNow_BroadcastOn_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *ShouldBroadcastNow_BroadcastOn_Call) RunAndReturn(run func() []broadcast.Channel) *ShouldBroadcastNow_BroadcastOn_Call {
	_c.Call.Return(run)
	return _c
}

// NewShouldBroadcastNow creates a new instance of ShouldBroadcastNow. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewShouldBroadcastNow(t interface {
	mock.TestingT
	Cleanup(func())
}) *ShouldBroadcastNow {
	mock := &ShouldBroadcastNow{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
