// Code generated by mockery. DO NOT EDIT.

package pipeline

import mock "github.com/stretchr/testify/mock"

// Pipe is an autogenerated mock type for the Pipe type
type Pipe struct {
	mock.Mock
}

type Pipe_Expecter struct {
	mock *mock.Mock
}

func (_m *Pipe) EXPECT() *Pipe_Expecter {
	return &Pipe_Expecter{mock: &_m.Mock}
}

// Handle provides a mock function with given fields: passable, next
func (_m *Pipe) Handle(passable interface{}, next func(interface{}) interface{}) interface{} {
	ret := _m.Called(passable, next)

	if len(ret) == 0 {
		panic("no return value specified for Handle")
	}

	var r0 interface{}
	if rf, ok := ret.Get(0).(func(interface{}, func(interface{}) interface{}) interface{}); ok {
		r0 = rf(passable, next)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(interface{})
		}
	}

	return r0
}

// Pipe_Handle_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Handle'
type Pipe_Handle_Call struct {
	*mock.Call
}

// Handle is a helper method to define mock.On call
//   - passable interface{}
//   - next func(interface{}) interface{}
func (_e *Pipe_Expecter) Handle(passable interface{}, next interface{}) *Pipe_Handle_Call {
	return &Pipe_Handle_Call{Call: _e.mock.On("Handle", passable, next)}
}

func (_c *Pipe_Handle_Call) Run(run func(passable interface{}, next func(interface{}) interface{})) *Pipe_Handle_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(interface{}), args[1].(func(interface{}) interface{}))
	})
	return _c
}

func (_c *Pipe_Handle_Call) Return(_a0 interface{}) *Pipe_Handle_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *Pipe_Handle_Call) RunAndReturn(run func(interface{}, func(interface{}) interface{}) interface{}) *Pipe_Handle_Call {
	_c.Call.Return(run)
	return _c
}

// NewPipe creates a new instance of Pipe. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewPipe(t interface {
	mock.TestingT
	Cleanup(func())
}) *Pipe {
	mock := &Pipe{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
