// Code generated by mockery. DO NOT EDIT.

package pipeline

import (
	pipeline "github.com/rusmanplatd/goravelframework/contracts/pipeline"
	mock "github.com/stretchr/testify/mock"
)

// Pipeline is an autogenerated mock type for the Pipeline type
type Pipeline struct {
	mock.Mock
}

type Pipeline_Expecter struct {
	mock *mock.Mock
}

func (_m *Pipeline) EXPECT() *Pipeline_Expecter {
	return &Pipeline_Expecter{mock: &_m.Mock}
}

// Pipe provides a mock function with given fields: pipes
func (_m *Pipeline) Pipe(pipes ...interface{}) pipeline.Pipeline {
	var _ca []interface{}
	_ca = append(_ca, pipes...)
	ret := _m.Called(_ca...)

	if len(ret) == 0 {
		panic("no return value specified for Pipe")
	}

	var r0 pipeline.Pipeline
	if rf, ok := ret.Get(0).(func(...interface{}) pipeline.Pipeline); ok {
		r0 = rf(pipes...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(pipeline.Pipeline)
		}
	}

	return r0
}

// Pipeline_Pipe_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Pipe'
type Pipeline_Pipe_Call struct {
	*mock.Call
}

// Pipe is a helper method to define mock.On call
//   - pipes ...interface{}
func (_e *Pipeline_Expecter) Pipe(pipes ...interface{}) *Pipeline_Pipe_Call {
	return &Pipeline_Pipe_Call{Call: _e.mock.On("Pipe",
		append([]interface{}{}, pipes...)...)}
}

func (_c *Pipeline_Pipe_Call) Run(run func(pipes ...interface{})) *Pipeline_Pipe_Call {
	_c.Call.Run(func(args mock.Arguments) {
		variadicArgs := make([]interface{}, len(args)-0)
		for i, a := range args[0:] {
			if a != nil {
				variadicArgs[i] = a.(interface{})
			}
		}
		run(variadicArgs...)
	})
	return _c
}

func (_c *Pipeline_Pipe_Call) Return(_a0 pipeline.Pipeline) *Pipeline_Pipe_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *Pipeline_Pipe_Call) RunAndReturn(run func(...interface{}) pipeline.Pipeline) *Pipeline_Pipe_Call {
	_c.Call.Return(run)
	return _c
}

// Send provides a mock function with given fields: passable
func (_m *Pipeline) Send(passable interface{}) pipeline.Pipeline {
	ret := _m.Called(passable)

	if len(ret) == 0 {
		panic("no return value specified for Send")
	}

	var r0 pipeline.Pipeline
	if rf, ok := ret.Get(0).(func(interface{}) pipeline.Pipeline); ok {
		r0 = rf(passable)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(pipeline.Pipeline)
		}
	}

	return r0
}

// Pipeline_Send_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Send'
type Pipeline_Send_Call struct {
	*mock.Call
}

// Send is a helper method to define mock.On call
//   - passable interface{}
func (_e *Pipeline_Expecter) Send(passable interface{}) *Pipeline_Send_Call {
	return &Pipeline_Send_Call{Call: _e.mock.On("Send", passable)}
}

func (_c *Pipeline_Send_Call) Run(run func(passable interface{})) *Pipeline_Send_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(interface{}))
	})
	return _c
}

func (_c *Pipeline_Send_Call) Return(_a0 pipeline.Pipeline) *Pipeline_Send_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *Pipeline_Send_Call) RunAndReturn(run func(interface{}) pipeline.Pipeline) *Pipeline_Send_Call {
	_c.Call.Return(run)
	return _c
}

// Then provides a mock function with given fields: destination
func (_m *Pipeline) Then(destination func(interface{}) interface{}) interface{} {
	ret := _m.Called(destination)

	if len(ret) == 0 {
		panic("no return value specified for Then")
	}

	var r0 interface{}
	if rf, ok := ret.Get(0).(func(func(interface{}) interface{}) interface{}); ok {
		r0 = rf(destination)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(interface{})
		}
	}

	return r0
}

// Pipeline_Then_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Then'
type Pipeline_Then_Call struct {
	*mock.Call
}

// Then is a helper method to define mock.On call
//   - destination func(interface{}) interface{}
func (_e *Pipeline_Expecter) Then(destination interface{}) *Pipeline_Then_Call {
	return &Pipeline_Then_Call{Call: _e.mock.On("Then", destination)}
}

func (_c *Pipeline_Then_Call) Run(run func(destination func(interface{}) interface{})) *Pipeline_Then_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(func(interface{}) interface{}))
	})
	return _c
}

func (_c *Pipeline_Then_Call) Return(_a0 interface{}) *Pipeline_Then_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *Pipeline_Then_Call) RunAndReturn(run func(func(interface{}) interface{}) interface{}) *Pipeline_Then_Call {
	_c.Call.Return(run)
	return _c
}

// ThenReturn provides a mock function with no fields
func (_m *Pipeline) ThenReturn() interface{} {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for ThenReturn")
	}

	var r0 interface{}
	if rf, ok := ret.Get(0).(func() interface{}); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(interface{})
		}
	}

	return r0
}

// Pipeline_ThenReturn_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ThenReturn'
type Pipeline_ThenReturn_Call struct {
	*mock.Call
}

// ThenReturn is a helper method to define mock.On call
func (_e *Pipeline_Expecter) ThenReturn() *Pipeline_ThenReturn_Call {
	return &Pipeline_ThenReturn_Call{Call: _e.mock.On("ThenReturn")}
}

func (_c *Pipeline_ThenReturn_Call) Run(run func()) *Pipeline_ThenReturn_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *Pipeline_ThenReturn_Call) Return(_a0 interface{}) *Pipeline_ThenReturn_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *Pipeline_ThenReturn_Call) RunAndReturn(run func() interface{}) *Pipeline_ThenReturn_Call {
	_c.Call.Return(run)
	return _c
}

// Through provides a mock function with given fields: pipes
func (_m *Pipeline) Through(pipes ...interface{}) pipeline.Pipeline {
	var _ca []interface{}
	_ca = append(_ca, pipes...)
	ret := _m.Called(_ca...)

	if len(ret) == 0 {
		panic("no return value specified for Through")
	}

	var r0 pipeline.Pipeline
	if rf, ok := ret.Get(0).(func(...interface{}) pipeline.Pipeline); ok {
		r0 = rf(pipes...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(pipeline.Pipeline)
		}
	}

	return r0
}

// Pipeline_Through_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Through'
type Pipeline_Through_Call struct {
	*mock.Call
}

// Through is a helper method to define mock.On call
//   - pipes ...interface{}
func (_e *Pipeline_Expecter) Through(pipes ...interface{}) *Pipeline_Through_Call {
	return &Pipeline_Through_Call{Call: _e.mock.On("Through",
		append([]interface{}{}, pipes...)...)}
}

func (_c *Pipeline_Through_Call) Run(run func(pipes ...interface{})) *Pipeline_Through_Call {
	_c.Call.Run(func(args mock.Arguments) {
		variadicArgs := make([]interface{}, len(args)-0)
		for i, a := range args[0:] {
			if a != nil {
				variadicArgs[i] = a.(interface{})
			}
		}
		run(variadicArgs...)
	})
	return _c
}

func (_c *Pipeline_Through_Call) Return(_a0 pipeline.Pipeline) *Pipeline_Through_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *Pipeline_Through_Call) RunAndReturn(run func(...interface{}) pipeline.Pipeline) *Pipeline_Through_Call {
	_c.Call.Return(run)
	return _c
}

// Via provides a mock function with given fields: method
func (_m *Pipeline) Via(method string) pipeline.Pipeline {
	ret := _m.Called(method)

	if len(ret) == 0 {
		panic("no return value specified for Via")
	}

	var r0 pipeline.Pipeline
	if rf, ok := ret.Get(0).(func(string) pipeline.Pipeline); ok {
		r0 = rf(method)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(pipeline.Pipeline)
		}
	}

	return r0
}

// Pipeline_Via_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Via'
type Pipeline_Via_Call struct {
	*mock.Call
}

// Via is a helper method to define mock.On call
//   - method string
func (_e *Pipeline_Expecter) Via(method interface{}) *Pipeline_Via_Call {
	return &Pipeline_Via_Call{Call: _e.mock.On("Via", method)}
}

func (_c *Pipeline_Via_Call) Run(run func(method string)) *Pipeline_Via_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string))
	})
	return _c
}

func (_c *Pipeline_Via_Call) Return(_a0 pipeline.Pipeline) *Pipeline_Via_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *Pipeline_Via_Call) RunAndReturn(run func(string) pipeline.Pipeline) *Pipeline_Via_Call {
	_c.Call.Return(run)
	return _c
}

// NewPipeline creates a new instance of Pipeline. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewPipeline(t interface {
	mock.TestingT
	Cleanup(func())
}) *Pipeline {
	mock := &Pipeline{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
