// Code generated by mockery. DO NOT EDIT.

package notification

import (
	notification "github.com/rusmanplatd/goravelframework/contracts/notification"
	mock "github.com/stretchr/testify/mock"
)

// Dispatcher is an autogenerated mock type for the Dispatcher type
type Dispatcher struct {
	mock.Mock
}

type Dispatcher_Expecter struct {
	mock *mock.Mock
}

func (_m *Dispatcher) EXPECT() *Dispatcher_Expecter {
	return &Dispatcher_Expecter{mock: &_m.Mock}
}

// Send provides a mock function with given fields: notifiables, _a1
func (_m *Dispatcher) Send(notifiables interface{}, _a1 notification.Notification) error {
	ret := _m.Called(notifiables, _a1)

	if len(ret) == 0 {
		panic("no return value specified for Send")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(interface{}, notification.Notification) error); ok {
		r0 = rf(notifiables, _a1)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Dispatcher_Send_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Send'
type Dispatcher_Send_Call struct {
	*mock.Call
}

// Send is a helper method to define mock.On call
//   - notifiables interface{}
//   - _a1 notification.Notification
func (_e *Dispatcher_Expecter) Send(notifiables interface{}, _a1 interface{}) *Dispatcher_Send_Call {
	return &Dispatcher_Send_Call{Call: _e.mock.On("Send", notifiables, _a1)}
}

func (_c *Dispatcher_Send_Call) Run(run func(notifiables interface{}, _a1 notification.Notification)) *Dispatcher_Send_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(interface{}), args[1].(notification.Notification))
	})
	return _c
}

func (_c *Dispatcher_Send_Call) Return(_a0 error) *Dispatcher_Send_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *Dispatcher_Send_Call) RunAndReturn(run func(interface{}, notification.Notification) error) *Dispatcher_Send_Call {
	_c.Call.Return(run)
	return _c
}

// SendNow provides a mock function with given fields: notifiables, _a1, channels
func (_m *Dispatcher) SendNow(notifiables interface{}, _a1 notification.Notification, channels ...string) error {
	_va := make([]interface{}, len(channels))
	for _i := range channels {
		_va[_i] = channels[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, notifiables, _a1)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	if len(ret) == 0 {
		panic("no return value specified for SendNow")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(interface{}, notification.Notification, ...string) error); ok {
		r0 = rf(notifiables, _a1, channels...)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Dispatcher_SendNow_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SendNow'
type Dispatcher_SendNow_Call struct {
	*mock.Call
}

// SendNow is a helper method to define mock.On call
//   - notifiables interface{}
//   - _a1 notification.Notification
//   - channels ...string
func (_e *Dispatcher_Expecter) SendNow(notifiables interface{}, _a1 interface{}, channels ...interface{}) *Dispatcher_SendNow_Call {
	return &Dispatcher_SendNow_Call{Call: _e.mock.On("SendNow",
		append([]interface{}{notifiables, _a1}, channels...)...)}
}

func (_c *Dispatcher_SendNow_Call) Run(run func(notifiables interface{}, _a1 notification.Notification, channels ...string)) *Dispatcher_SendNow_Call {
	_c.Call.Run(func(args mock.Arguments) {
		variadicArgs := make([]string, len(args)-2)
		for i, a := range args[2:] {
			if a != nil {
				variadicArgs[i] = a.(string)
			}
		}
		run(args[0].(interface{}), args[1].(notification.Notification), variadicArgs...)
	})
	return _c
}

func (_c *Dispatcher_SendNow_Call) Return(_a0 error) *Dispatcher_SendNow_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *Dispatcher_SendNow_Call) RunAndReturn(run func(interface{}, notification.Notification, ...string) error) *Dispatcher_SendNow_Call {
	_c.Call.Return(run)
	return _c
}

// NewDispatcher creates a new instance of Dispatcher. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewDispatcher(t interface {
	mock.TestingT
	Cleanup(func())
}) *Dispatcher {
	mock := &Dispatcher{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
