// Code generated by mockery. DO NOT EDIT.

package notification

import (
	notification "github.com/goravel/framework/contracts/notification"
	mock "github.com/stretchr/testify/mock"
)

// Factory is an autogenerated mock type for the Factory type
type Factory struct {
	mock.Mock
}

type Factory_Expecter struct {
	mock *mock.Mock
}

func (_m *Factory) EXPECT() *Factory_Expecter {
	return &Factory_Expecter{mock: &_m.Mock}
}

// Channel provides a mock function with given fields: name
func (_m *Factory) Channel(name string) (notification.Channel, error) {
	ret := _m.Called(name)

	if len(ret) == 0 {
		panic("no return value specified for Channel")
	}

	var r0 notification.Channel
	var r1 error
	if rf, ok := ret.Get(0).(func(string) (notification.Channel, error)); ok {
		return rf(name)
	}
	if rf, ok := ret.Get(0).(func(string) notification.Channel); ok {
		r0 = rf(name)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(notification.Channel)
		}
	}

	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(name)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Factory_Channel_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Channel'
type Factory_Channel_Call struct {
	*mock.Call
}

// Channel is a helper method to define mock.On call
//   - name string
func (_e *Factory_Expecter) Channel(name interface{}) *Factory_Channel_Call {
	return &Factory_Channel_Call{Call: _e.mock.On("Channel", name)}
}

func (_c *Factory_Channel_Call) Run(run func(name string)) *Factory_Channel_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string))
	})
	return _c
}

func (_c *Factory_Channel_Call) Return(_a0 notification.Channel, _a1 error) *Factory_Channel_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *Factory_Channel_Call) RunAndReturn(run func(string) (notification.Channel, error)) *Factory_Channel_Call {
	_c.Call.Return(run)
	return _c
}

// Send provides a mock function with given fields: notifiables, _a1
func (_m *Factory) Send(notifiables interface{}, _a1 notification.Notification) error {
	ret := _m.Called(notifiables, _a1)

	if len(ret) == 0 {
		panic("no return value specified for Send")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(interface{}, notification.Notification) error); ok {
		r0 = rf(notifiables, _a1)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Factory_Send_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Send'
type Factory_Send_Call struct {
	*mock.Call
}

// Send is a helper method to define mock.On call
//   - notifiables interface{}
//   - _a1 notification.Notification
func (_e *Factory_Expecter) Send(notifiables interface{}, _a1 interface{}) *Factory_Send_Call {
	return &Factory_Send_Call{Call: _e.mock.On("Send", notifiables, _a1)}
}

func (_c *Factory_Send_Call) Run(run func(notifiables interface{}, _a1 notification.Notification)) *Factory_Send_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(interface{}), args[1].(notification.Notification))
	})
	return _c
}

func (_c *Factory_Send_Call) Return(_a0 error) *Factory_Send_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *Factory_Send_Call) RunAndReturn(run func(interface{}, notification.Notification) error) *Factory_Send_Call {
	_c.Call.Return(run)
	return _c
}

// SendNow provides a mock function with given fields: notifiables, _a1, channels
func (_m *Factory) SendNow(notifiables interface{}, _a1 notification.Notification, channels ...string) error {
	_va := make([]interface{}, len(channels))
	for _i := range channels {
		_va[_i] = channels[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, notifiables, _a1)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	if len(ret) == 0 {
		panic("no return value specified for SendNow")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(interface{}, notification.Notification, ...string) error); ok {
		r0 = rf(notifiables, _a1, channels...)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Factory_SendNow_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SendNow'
type Factory_SendNow_Call struct {
	*mock.Call
}

// SendNow is a helper method to define mock.On call
//   - notifiables interface{}
//   - _a1 notification.Notification
//   - channels ...string
func (_e *Factory_Expecter) SendNow(notifiables interface{}, _a1 interface{}, channels ...interface{}) *Factory_SendNow_Call {
	return &Factory_SendNow_Call{Call: _e.mock.On("SendNow",
		append([]interface{}{notifiables, _a1}, channels...)...)}
}

func (_c *Factory_SendNow_Call) Run(run func(notifiables interface{}, _a1 notification.Notification, channels ...string)) *Factory_SendNow_Call {
	_c.Call.Run(func(args mock.Arguments) {
		variadicArgs := make([]string, len(args)-2)
		for i, a := range args[2:] {
			if a != nil {
				variadicArgs[i] = a.(string)
			}
		}
		run(args[0].(interface{}), args[1].(notification.Notification), variadicArgs...)
	})
	return _c
}

func (_c *Factory_SendNow_Call) Return(_a0 error) *Factory_SendNow_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *Factory_SendNow_Call) RunAndReturn(run func(interface{}, notification.Notification, ...string) error) *Factory_SendNow_Call {
	_c.Call.Return(run)
	return _c
}

// NewFactory creates a new instance of Factory. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewFactory(t interface {
	mock.TestingT
	Cleanup(func())
}) *Factory {
	mock := &Factory{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
