// Code generated by mockery. DO NOT EDIT.

package notification

import mock "github.com/stretchr/testify/mock"

// HasLocale is an autogenerated mock type for the HasLocale type
type HasLocale struct {
	mock.Mock
}

type HasLocale_Expecter struct {
	mock *mock.Mock
}

func (_m *HasLocale) EXPECT() *HasLocale_Expecter {
	return &HasLocale_Expecter{mock: &_m.Mock}
}

// Locale provides a mock function with no fields
func (_m *HasLocale) Locale() string {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for Locale")
	}

	var r0 string
	if rf, ok := ret.Get(0).(func() string); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(string)
	}

	return r0
}

// HasLocale_Locale_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Locale'
type HasLocale_Locale_Call struct {
	*mock.Call
}

// Locale is a helper method to define mock.On call
func (_e *HasLocale_Expecter) Locale() *HasLocale_Locale_Call {
	return &HasLocale_Locale_Call{Call: _e.mock.On("Locale")}
}

func (_c *HasLocale_Locale_Call) Run(run func()) *HasLocale_Locale_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *HasLocale_Locale_Call) Return(_a0 string) *HasLocale_Locale_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *HasLocale_Locale_Call) RunAndReturn(run func() string) *HasLocale_Locale_Call {
	_c.Call.Return(run)
	return _c
}

// NewHasLocale creates a new instance of HasLocale. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewHasLocale(t interface {
	mock.TestingT
	Cleanup(func())
}) *HasLocale {
	mock := &HasLocale{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
