// Code generated by mockery. DO NOT EDIT.

package notification

import (
	mail "github.com/goravel/framework/contracts/mail"
	mock "github.com/stretchr/testify/mock"

	notification "github.com/goravel/framework/contracts/notification"
)

// Notification is an autogenerated mock type for the Notification type
type Notification struct {
	mock.Mock
}

type Notification_Expecter struct {
	mock *mock.Mock
}

func (_m *Notification) EXPECT() *Notification_Expecter {
	return &Notification_Expecter{mock: &_m.Mock}
}

// ToArray provides a mock function with given fields: notifiable
func (_m *Notification) ToArray(notifiable interface{}) map[string]interface{} {
	ret := _m.Called(notifiable)

	if len(ret) == 0 {
		panic("no return value specified for ToArray")
	}

	var r0 map[string]interface{}
	if rf, ok := ret.Get(0).(func(interface{}) map[string]interface{}); ok {
		r0 = rf(notifiable)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(map[string]interface{})
		}
	}

	return r0
}

// Notification_ToArray_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ToArray'
type Notification_ToArray_Call struct {
	*mock.Call
}

// ToArray is a helper method to define mock.On call
//   - notifiable interface{}
func (_e *Notification_Expecter) ToArray(notifiable interface{}) *Notification_ToArray_Call {
	return &Notification_ToArray_Call{Call: _e.mock.On("ToArray", notifiable)}
}

func (_c *Notification_ToArray_Call) Run(run func(notifiable interface{})) *Notification_ToArray_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(interface{}))
	})
	return _c
}

func (_c *Notification_ToArray_Call) Return(_a0 map[string]interface{}) *Notification_ToArray_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *Notification_ToArray_Call) RunAndReturn(run func(interface{}) map[string]interface{}) *Notification_ToArray_Call {
	_c.Call.Return(run)
	return _c
}

// ToDatabase provides a mock function with given fields: notifiable
func (_m *Notification) ToDatabase(notifiable interface{}) *notification.DatabaseMessage {
	ret := _m.Called(notifiable)

	if len(ret) == 0 {
		panic("no return value specified for ToDatabase")
	}

	var r0 *notification.DatabaseMessage
	if rf, ok := ret.Get(0).(func(interface{}) *notification.DatabaseMessage); ok {
		r0 = rf(notifiable)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*notification.DatabaseMessage)
		}
	}

	return r0
}

// Notification_ToDatabase_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ToDatabase'
type Notification_ToDatabase_Call struct {
	*mock.Call
}

// ToDatabase is a helper method to define mock.On call
//   - notifiable interface{}
func (_e *Notification_Expecter) ToDatabase(notifiable interface{}) *Notification_ToDatabase_Call {
	return &Notification_ToDatabase_Call{Call: _e.mock.On("ToDatabase", notifiable)}
}

func (_c *Notification_ToDatabase_Call) Run(run func(notifiable interface{})) *Notification_ToDatabase_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(interface{}))
	})
	return _c
}

func (_c *Notification_ToDatabase_Call) Return(_a0 *notification.DatabaseMessage) *Notification_ToDatabase_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *Notification_ToDatabase_Call) RunAndReturn(run func(interface{}) *notification.DatabaseMessage) *Notification_ToDatabase_Call {
	_c.Call.Return(run)
	return _c
}

// ToMail provides a mock function with given fields: notifiable
func (_m *Notification) ToMail(notifiable interface{}) mail.Mailable {
	ret := _m.Called(notifiable)

	if len(ret) == 0 {
		panic("no return value specified for ToMail")
	}

	var r0 mail.Mailable
	if rf, ok := ret.Get(0).(func(interface{}) mail.Mailable); ok {
		r0 = rf(notifiable)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(mail.Mailable)
		}
	}

	return r0
}

// Notification_ToMail_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ToMail'
type Notification_ToMail_Call struct {
	*mock.Call
}

// ToMail is a helper method to define mock.On call
//   - notifiable interface{}
func (_e *Notification_Expecter) ToMail(notifiable interface{}) *Notification_ToMail_Call {
	return &Notification_ToMail_Call{Call: _e.mock.On("ToMail", notifiable)}
}

func (_c *Notification_ToMail_Call) Run(run func(notifiable interface{})) *Notification_ToMail_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(interface{}))
	})
	return _c
}

func (_c *Notification_ToMail_Call) Return(_a0 mail.Mailable) *Notification_ToMail_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *Notification_ToMail_Call) RunAndReturn(run func(interface{}) mail.Mailable) *Notification_ToMail_Call {
	_c.Call.Return(run)
	return _c
}

// Via provides a mock function with given fields: notifiable
func (_m *Notification) Via(notifiable interface{}) []string {
	ret := _m.Called(notifiable)

	if len(ret) == 0 {
		panic("no return value specified for Via")
	}

	var r0 []string
	if rf, ok := ret.Get(0).(func(interface{}) []string); ok {
		r0 = rf(notifiable)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]string)
		}
	}

	return r0
}

// Notification_Via_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Via'
type Notification_Via_Call struct {
	*mock.Call
}

// Via is a helper method to define mock.On call
//   - notifiable interface{}
func (_e *Notification_Expecter) Via(notifiable interface{}) *Notification_Via_Call {
	return &Notification_Via_Call{Call: _e.mock.On("Via", notifiable)}
}

func (_c *Notification_Via_Call) Run(run func(notifiable interface{})) *Notification_Via_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(interface{}))
	})
	return _c
}

func (_c *Notification_Via_Call) Return(_a0 []string) *Notification_Via_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *Notification_Via_Call) RunAndReturn(run func(interface{}) []string) *Notification_Via_Call {
	_c.Call.Return(run)
	return _c
}

// NewNotification creates a new instance of Notification. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewNotification(t interface {
	mock.TestingT
	Cleanup(func())
}) *Notification {
	mock := &Notification{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
