// Code generated by mockery. DO NOT EDIT.

package notification

import mock "github.com/stretchr/testify/mock"

// ShouldSend is an autogenerated mock type for the ShouldSend type
type ShouldSend struct {
	mock.Mock
}

type ShouldSend_Expecter struct {
	mock *mock.Mock
}

func (_m *ShouldSend) EXPECT() *ShouldSend_Expecter {
	return &ShouldSend_Expecter{mock: &_m.Mock}
}

// ShouldSend provides a mock function with given fields: notifiable, channel
func (_m *ShouldSend) ShouldSend(notifiable interface{}, channel string) bool {
	ret := _m.Called(notifiable, channel)

	if len(ret) == 0 {
		panic("no return value specified for ShouldSend")
	}

	var r0 bool
	if rf, ok := ret.Get(0).(func(interface{}, string) bool); ok {
		r0 = rf(notifiable, channel)
	} else {
		r0 = ret.Get(0).(bool)
	}

	return r0
}

// ShouldSend_ShouldSend_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ShouldSend'
type ShouldSend_ShouldSend_Call struct {
	*mock.Call
}

// ShouldSend is a helper method to define mock.On call
//   - notifiable interface{}
//   - channel string
func (_e *ShouldSend_Expecter) ShouldSend(notifiable interface{}, channel interface{}) *ShouldSend_ShouldSend_Call {
	return &ShouldSend_ShouldSend_Call{Call: _e.mock.On("ShouldSend", notifiable, channel)}
}

func (_c *ShouldSend_ShouldSend_Call) Run(run func(notifiable interface{}, channel string)) *ShouldSend_ShouldSend_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(interface{}), args[1].(string))
	})
	return _c
}

func (_c *ShouldSend_ShouldSend_Call) Return(_a0 bool) *ShouldSend_ShouldSend_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *ShouldSend_ShouldSend_Call) RunAndReturn(run func(interface{}, string) bool) *ShouldSend_ShouldSend_Call {
	_c.Call.Return(run)
	return _c
}

// NewShouldSend creates a new instance of ShouldSend. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewShouldSend(t interface {
	mock.TestingT
	Cleanup(func())
}) *ShouldSend {
	mock := &ShouldSend{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
