// Code generated by mockery. DO NOT EDIT.

package notification

import mock "github.com/stretchr/testify/mock"

// ViaConnections is an autogenerated mock type for the ViaConnections type
type ViaConnections struct {
	mock.Mock
}

type ViaConnections_Expecter struct {
	mock *mock.Mock
}

func (_m *ViaConnections) EXPECT() *ViaConnections_Expecter {
	return &ViaConnections_Expecter{mock: &_m.Mock}
}

// ViaConnections provides a mock function with no fields
func (_m *ViaConnections) ViaConnections() map[string]string {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for ViaConnections")
	}

	var r0 map[string]string
	if rf, ok := ret.Get(0).(func() map[string]string); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(map[string]string)
		}
	}

	return r0
}

// ViaConnections_ViaConnections_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ViaConnections'
type ViaConnections_ViaConnections_Call struct {
	*mock.Call
}

// ViaConnections is a helper method to define mock.On call
func (_e *ViaConnections_Expecter) ViaConnections() *ViaConnections_ViaConnections_Call {
	return &ViaConnections_ViaConnections_Call{Call: _e.mock.On("ViaConnections")}
}

func (_c *ViaConnections_ViaConnections_Call) Run(run func()) *ViaConnections_ViaConnections_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *ViaConnections_ViaConnections_Call) Return(_a0 map[string]string) *ViaConnections_ViaConnections_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *ViaConnections_ViaConnections_Call) RunAndReturn(run func() map[string]string) *ViaConnections_ViaConnections_Call {
	_c.Call.Return(run)
	return _c
}

// NewViaConnections creates a new instance of ViaConnections. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewViaConnections(t interface {
	mock.TestingT
	Cleanup(func())
}) *ViaConnections {
	mock := &ViaConnections{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
