// Code generated by mockery. DO NOT EDIT.

package notification

import mock "github.com/stretchr/testify/mock"

// ViaQueues is an autogenerated mock type for the ViaQueues type
type ViaQueues struct {
	mock.Mock
}

type ViaQueues_Expecter struct {
	mock *mock.Mock
}

func (_m *ViaQueues) EXPECT() *ViaQueues_Expecter {
	return &ViaQueues_Expecter{mock: &_m.Mock}
}

// ViaQueues provides a mock function with no fields
func (_m *ViaQueues) ViaQueues() map[string]string {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for ViaQueues")
	}

	var r0 map[string]string
	if rf, ok := ret.Get(0).(func() map[string]string); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(map[string]string)
		}
	}

	return r0
}

// ViaQueues_ViaQueues_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ViaQueues'
type ViaQueues_ViaQueues_Call struct {
	*mock.Call
}

// ViaQueues is a helper method to define mock.On call
func (_e *ViaQueues_Expecter) ViaQueues() *ViaQueues_ViaQueues_Call {
	return &ViaQueues_ViaQueues_Call{Call: _e.mock.On("ViaQueues")}
}

func (_c *ViaQueues_ViaQueues_Call) Run(run func()) *ViaQueues_ViaQueues_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *ViaQueues_ViaQueues_Call) Return(_a0 map[string]string) *ViaQueues_ViaQueues_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *ViaQueues_ViaQueues_Call) RunAndReturn(run func() map[string]string) *ViaQueues_ViaQueues_Call {
	_c.Call.Return(run)
	return _c
}

// NewViaQueues creates a new instance of ViaQueues. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewViaQueues(t interface {
	mock.TestingT
	Cleanup(func())
}) *ViaQueues {
	mock := &ViaQueues{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
