// Code generated by mockery. DO NOT EDIT.

package notification

import mock "github.com/stretchr/testify/mock"

// WithDelay is an autogenerated mock type for the WithDelay type
type WithDelay struct {
	mock.Mock
}

type WithDelay_Expecter struct {
	mock *mock.Mock
}

func (_m *WithDelay) EXPECT() *WithDelay_Expecter {
	return &WithDelay_Expecter{mock: &_m.Mock}
}

// WithDelay provides a mock function with given fields: notifiable, channel
func (_m *WithDelay) WithDelay(notifiable interface{}, channel string) int {
	ret := _m.Called(notifiable, channel)

	if len(ret) == 0 {
		panic("no return value specified for WithDelay")
	}

	var r0 int
	if rf, ok := ret.Get(0).(func(interface{}, string) int); ok {
		r0 = rf(notifiable, channel)
	} else {
		r0 = ret.Get(0).(int)
	}

	return r0
}

// WithDelay_WithDelay_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'WithDelay'
type WithDelay_WithDelay_Call struct {
	*mock.Call
}

// WithDelay is a helper method to define mock.On call
//   - notifiable interface{}
//   - channel string
func (_e *WithDelay_Expecter) WithDelay(notifiable interface{}, channel interface{}) *WithDelay_WithDelay_Call {
	return &WithDelay_WithDelay_Call{Call: _e.mock.On("WithDelay", notifiable, channel)}
}

func (_c *WithDelay_WithDelay_Call) Run(run func(notifiable interface{}, channel string)) *WithDelay_WithDelay_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(interface{}), args[1].(string))
	})
	return _c
}

func (_c *WithDelay_WithDelay_Call) Return(_a0 int) *WithDelay_WithDelay_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *WithDelay_WithDelay_Call) RunAndReturn(run func(interface{}, string) int) *WithDelay_WithDelay_Call {
	_c.Call.Return(run)
	return _c
}

// NewWithDelay creates a new instance of WithDelay. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewWithDelay(t interface {
	mock.TestingT
	Cleanup(func())
}) *WithDelay {
	mock := &WithDelay{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
