// Code generated by mockery. DO NOT EDIT.

package event

import mock "github.com/stretchr/testify/mock"

// QueueableListener is an autogenerated mock type for the QueueableListener type
type QueueableListener struct {
	mock.Mock
}

type QueueableListener_Expecter struct {
	mock *mock.Mock
}

func (_m *QueueableListener) EXPECT() *QueueableListener_Expecter {
	return &QueueableListener_Expecter{mock: &_m.Mock}
}

// ViaConnection provides a mock function with no fields
func (_m *QueueableListener) ViaConnection() string {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for ViaConnection")
	}

	var r0 string
	if rf, ok := ret.Get(0).(func() string); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(string)
	}

	return r0
}

// QueueableListener_ViaConnection_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ViaConnection'
type QueueableListener_ViaConnection_Call struct {
	*mock.Call
}

// ViaConnection is a helper method to define mock.On call
func (_e *QueueableListener_Expecter) ViaConnection() *QueueableListener_ViaConnection_Call {
	return &QueueableListener_ViaConnection_Call{Call: _e.mock.On("ViaConnection")}
}

func (_c *QueueableListener_ViaConnection_Call) Run(run func()) *QueueableListener_ViaConnection_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *QueueableListener_ViaConnection_Call) Return(_a0 string) *QueueableListener_ViaConnection_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *QueueableListener_ViaConnection_Call) RunAndReturn(run func() string) *QueueableListener_ViaConnection_Call {
	_c.Call.Return(run)
	return _c
}

// ViaQueue provides a mock function with no fields
func (_m *QueueableListener) ViaQueue() string {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for ViaQueue")
	}

	var r0 string
	if rf, ok := ret.Get(0).(func() string); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(string)
	}

	return r0
}

// QueueableListener_ViaQueue_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ViaQueue'
type QueueableListener_ViaQueue_Call struct {
	*mock.Call
}

// ViaQueue is a helper method to define mock.On call
func (_e *QueueableListener_Expecter) ViaQueue() *QueueableListener_ViaQueue_Call {
	return &QueueableListener_ViaQueue_Call{Call: _e.mock.On("ViaQueue")}
}

func (_c *QueueableListener_ViaQueue_Call) Run(run func()) *QueueableListener_ViaQueue_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *QueueableListener_ViaQueue_Call) Return(_a0 string) *QueueableListener_ViaQueue_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *QueueableListener_ViaQueue_Call) RunAndReturn(run func() string) *QueueableListener_ViaQueue_Call {
	_c.Call.Return(run)
	return _c
}

// WithDelay provides a mock function with no fields
func (_m *QueueableListener) WithDelay() int {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for WithDelay")
	}

	var r0 int
	if rf, ok := ret.Get(0).(func() int); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(int)
	}

	return r0
}

// QueueableListener_WithDelay_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'WithDelay'
type QueueableListener_WithDelay_Call struct {
	*mock.Call
}

// WithDelay is a helper method to define mock.On call
func (_e *QueueableListener_Expecter) WithDelay() *QueueableListener_WithDelay_Call {
	return &QueueableListener_WithDelay_Call{Call: _e.mock.On("WithDelay")}
}

func (_c *QueueableListener_WithDelay_Call) Run(run func()) *QueueableListener_WithDelay_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *QueueableListener_WithDelay_Call) Return(_a0 int) *QueueableListener_WithDelay_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *QueueableListener_WithDelay_Call) RunAndReturn(run func() int) *QueueableListener_WithDelay_Call {
	_c.Call.Return(run)
	return _c
}

// NewQueueableListener creates a new instance of QueueableListener. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewQueueableListener(t interface {
	mock.TestingT
	Cleanup(func())
}) *QueueableListener {
	mock := &QueueableListener{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
