// Code generated by mockery. DO NOT EDIT.

package event

import mock "github.com/stretchr/testify/mock"

// ShouldBroadcast is an autogenerated mock type for the ShouldBroadcast type
type ShouldBroadcast struct {
	mock.Mock
}

type ShouldBroadcast_Expecter struct {
	mock *mock.Mock
}

func (_m *ShouldBroadcast) EXPECT() *ShouldBroadcast_Expecter {
	return &ShouldBroadcast_Expecter{mock: &_m.Mock}
}

// BroadcastOn provides a mock function with no fields
func (_m *ShouldBroadcast) BroadcastOn() []string {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for BroadcastOn")
	}

	var r0 []string
	if rf, ok := ret.Get(0).(func() []string); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]string)
		}
	}

	return r0
}

// ShouldBroadcast_BroadcastOn_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'BroadcastOn'
type ShouldBroadcast_BroadcastOn_Call struct {
	*mock.Call
}

// BroadcastOn is a helper method to define mock.On call
func (_e *ShouldBroadcast_Expecter) BroadcastOn() *ShouldBroadcast_BroadcastOn_Call {
	return &ShouldBroadcast_BroadcastOn_Call{Call: _e.mock.On("BroadcastOn")}
}

func (_c *ShouldBroadcast_BroadcastOn_Call) Run(run func()) *ShouldBroadcast_BroadcastOn_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *ShouldBroadcast_BroadcastOn_Call) Return(_a0 []string) *ShouldBroadcast_BroadcastOn_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *ShouldBroadcast_BroadcastOn_Call) RunAndReturn(run func() []string) *ShouldBroadcast_BroadcastOn_Call {
	_c.Call.Return(run)
	return _c
}

// BroadcastWhen provides a mock function with no fields
func (_m *ShouldBroadcast) BroadcastWhen() bool {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for BroadcastWhen")
	}

	var r0 bool
	if rf, ok := ret.Get(0).(func() bool); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(bool)
	}

	return r0
}

// ShouldBroadcast_BroadcastWhen_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'BroadcastWhen'
type ShouldBroadcast_BroadcastWhen_Call struct {
	*mock.Call
}

// BroadcastWhen is a helper method to define mock.On call
func (_e *ShouldBroadcast_Expecter) BroadcastWhen() *ShouldBroadcast_BroadcastWhen_Call {
	return &ShouldBroadcast_BroadcastWhen_Call{Call: _e.mock.On("BroadcastWhen")}
}

func (_c *ShouldBroadcast_BroadcastWhen_Call) Run(run func()) *ShouldBroadcast_BroadcastWhen_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *ShouldBroadcast_BroadcastWhen_Call) Return(_a0 bool) *ShouldBroadcast_BroadcastWhen_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *ShouldBroadcast_BroadcastWhen_Call) RunAndReturn(run func() bool) *ShouldBroadcast_BroadcastWhen_Call {
	_c.Call.Return(run)
	return _c
}

// NewShouldBroadcast creates a new instance of ShouldBroadcast. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewShouldBroadcast(t interface {
	mock.TestingT
	Cleanup(func())
}) *ShouldBroadcast {
	mock := &ShouldBroadcast{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
