// Code generated by mockery. DO NOT EDIT.

package event

import mock "github.com/stretchr/testify/mock"

// ShouldDispatchAfterCommit is an autogenerated mock type for the ShouldDispatchAfterCommit type
type ShouldDispatchAfterCommit struct {
	mock.Mock
}

type ShouldDispatchAfterCommit_Expecter struct {
	mock *mock.Mock
}

func (_m *ShouldDispatchAfterCommit) EXPECT() *ShouldDispatchAfterCommit_Expecter {
	return &ShouldDispatchAfterCommit_Expecter{mock: &_m.Mock}
}

// ShouldDispatchAfterCommit provides a mock function with no fields
func (_m *ShouldDispatchAfterCommit) ShouldDispatchAfterCommit() bool {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for ShouldDispatchAfterCommit")
	}

	var r0 bool
	if rf, ok := ret.Get(0).(func() bool); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(bool)
	}

	return r0
}

// ShouldDispatchAfterCommit_ShouldDispatchAfterCommit_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ShouldDispatchAfterCommit'
type ShouldDispatchAfterCommit_ShouldDispatchAfterCommit_Call struct {
	*mock.Call
}

// ShouldDispatchAfterCommit is a helper method to define mock.On call
func (_e *ShouldDispatchAfterCommit_Expecter) ShouldDispatchAfterCommit() *ShouldDispatchAfterCommit_ShouldDispatchAfterCommit_Call {
	return &ShouldDispatchAfterCommit_ShouldDispatchAfterCommit_Call{Call: _e.mock.On("ShouldDispatchAfterCommit")}
}

func (_c *ShouldDispatchAfterCommit_ShouldDispatchAfterCommit_Call) Run(run func()) *ShouldDispatchAfterCommit_ShouldDispatchAfterCommit_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *ShouldDispatchAfterCommit_ShouldDispatchAfterCommit_Call) Return(_a0 bool) *ShouldDispatchAfterCommit_ShouldDispatchAfterCommit_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *ShouldDispatchAfterCommit_ShouldDispatchAfterCommit_Call) RunAndReturn(run func() bool) *ShouldDispatchAfterCommit_ShouldDispatchAfterCommit_Call {
	_c.Call.Return(run)
	return _c
}

// NewShouldDispatchAfterCommit creates a new instance of ShouldDispatchAfterCommit. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewShouldDispatchAfterCommit(t interface {
	mock.TestingT
	Cleanup(func())
}) *ShouldDispatchAfterCommit {
	mock := &ShouldDispatchAfterCommit{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
